### ISSUE TITLE
Idee: Template HTML als Fragment anbieten, damit das leicht überschrieben werden kann

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/iwcc#10]

**Comment by IngoWinter** [comment]
@skerbis wollte eine REX_VAR draus machen :)
Mir ist es eigentlich egal. Wenn ihr euch einigt machen wirs einfach so - die aktuelle Template Geschichte ist bei Änderungen besschissen zu updaten.

**Comment by olien** [comment]
Ok. Er macht das schon gut :-)

**Comment by skerbis** [comment]
Abwarten. In REDAXO 5.9 wird man Templates auch über einen Namen einbinden können.

**Comment by IngoWinter** [comment]
mir schwebt vor, bei der installation zu prüfen, ob es ein template "iwcc" gibt. wenn ja, das überschreiben, wenn nein neu anlegen. spricht da irgendwas gegen? aktuell wird immer ein neues template angelegt.

**Comment by olien** [comment]
Von mir aus. Sollte nur in der Anleitung stehen. Nicht das jemand sich das Template anpasst und das wird dann überschrieben.

**Comment by IngoWinter** [comment]
@tbaddade magst du da auch noch was zu sagen? du hast oben den daumen hoch für fragment gegeben.

**Comment by skerbis** [comment]
Sehe es auch so. Fragment ist ne gute Lösung da es für individuelle Anpassungen überschrieben werden kann. Also Fragment + value für die Auslieferung

**Comment by IngoWinter** [comment]
Kann ich mir das irgendwo abkupfern? Hab ewig nix mehr mit REX_VALUE gemacht ^^

**Comment by skerbis** [comment]
Ja https://github.com/FriendsOfREDAXO/global_settings/blob/master/lib/rex_var_global_var.php

**Comment by IngoWinter** [comment]
Das ist ja einfach. Dann mach ich REX_IWCC und lege den Templatecode in ein Fragment. Alle glücklich :)

**Comment by tbaddade** [comment]
> magst du da auch noch was zu sagen? du hast oben den daumen hoch für fragment gegeben.

Fragment anstatt Template. Lässt sich für das AddOn selbst auch leichter aktualisieren.

**Comment by IngoWinter** [comment]
`REX_IWCC[]` isses nun :)

**Comment by olien** [comment]
top
