### ISSUE TITLE
Klassendefinition zu den Cookie-Gruppen

### ISSUE THREAD

**Issue by vedatoezdemir** [FriendsOfREDAXO/iwcc#105]
Können die Checkboxen in der iwcc_box.php mit CSS-Klassen erweitert werden? Somit würde jeder Checkbox eigene Klassennamen haben und kann auch für Frontend dementsprechend formatiert werden.

z. B. die Zeilen 28 und 42 mit "cookie-'.$cookiegroup['uid'].'" in der Klasse erweitern.

![Bildschirmfoto 2020-11-26 um 13 26 13](https://user-images.githubusercontent.com/25198918/100350939-fb4e5680-2fea-11eb-9b54-d933574c581d.png)

so kann ich jede Cookie für Frontend individuell anpassen

![Bildschirmfoto 2020-11-26 um 13 25 03](https://user-images.githubusercontent.com/25198918/100350857-d4902000-2fea-11eb-8104-576979cd54a6.png)

**Comment by IngoWinter** [comment]
Vielleicht möchtest du dich mit @aeberhard kurzschliessen, der will auch an der Box rumbauen: https://github.com/FriendsOfREDAXO/iwcc/issues/104
Allerdings kannst du auch über CCS auf das data Attribut zugreifen: https://developer.mozilla.org/de/docs/Web/CSS/Attributselektoren

**Comment by vedatoezdemir** [comment]
@IngoWinter die data-Attribute bezieht sich ja auf das eigene Element. Ich muss die Klasse schon in der übergeordneten Element haben damit ich die untergeordnete Elemente z. B. das DIV-Element mit der Klasse ".state" ansprechen damit ich z. B. Pseudo-Klassen definieren kann.

**Comment by IngoWinter** [comment]
so: `[data-uid="xyz"] + div:after {}` ?

**Comment by vedatoezdemir** [comment]
Danke @IngoWinter. Stimmt so könnte ich auch zum Ziel kommen.
