### ISSUE TITLE
Angelegte und wieder gelöschte Gruppe wird nicht gelöscht

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/iwcc#11]
![image](https://user-images.githubusercontent.com/330516/68570568-48ec3580-0461-11ea-9062-10895d40db8e.png)

![image](https://user-images.githubusercontent.com/330516/68570594-56a1bb00-0461-11ea-96c6-c2b408874fe3.png)

**Comment by IngoWinter** [comment]
im frontend werden die daten aus einem cachefile geholt, nicht direkt aus der datenbank. das cachefile wurde nur beim ep rex_form_save neu generiert und nicht beim löschen. ist hiermit https://github.com/FriendsOfREDAXO/iwcc/commit/83fede611255810d0b0d0cf0d0b212dcd440f531 gefixt
