### ISSUE TITLE
Leerer Datenschutzlink bei Cookie wird nicht beachtet

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/iwcc#15]
<img width="1412" alt="Bildschirmfoto 2019-11-12 um 12 12 01" src="https://user-images.githubusercontent.com/791247/68667427-3992e800-0546-11ea-96fb-251a8bdc29df.png">

Es wird ein Link auf das Impressum der Domain gesetzt.

**Comment by IngoWinter** [comment]
ist in https://github.com/FriendsOfREDAXO/iwcc/commit/83ee5f63e981a5a8f5b301b2100b36f97e60c331 gefixt
