### ISSUE TITLE
Cookies werden nicht entfernt

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/iwcc#16]
Gesetzte Cookies werden nach Abwahl (Einstellungen bearbeiten) nicht entfernt.

**Comment by IngoWinter** [comment]
Die Cookies werden hier entfernt: https://github.com/FriendsOfREDAXO/iwcc/blob/master/assets/iwcc_frontend.js#L96-L104
Stimmen Domain und Pfad bei den nicht löschbaren Cookies damit überein? Und weils Javascript Gerödel ist: ist das browserunabhängig?

**Comment by skerbis** [comment]
hmm ok ... es scheint komplizierter zu sein ...

**Comment by skerbis** [comment]
ich habe _pk_id angegeben ... aber es müsste wohl so aussehen: `_pk_id.01.f5be` bei Matomo 
Scheint so als ob jede Seite die in Matomo verwaltet wird  einen eigenen Cookie namen bekommt

**Comment by skerbis** [comment]
Auch dann wird's nicht entfernt

**Comment by IngoWinter** [comment]
@skerbis du kannst nochmal testen, es hat sich nur die iwcc_frontend.js https://github.com/FriendsOfREDAXO/iwcc/blob/master/assets/iwcc_frontend.js geändert. sollte nun klappen :)

**Comment by skerbis** [comment]
Perfekt! Danke schön
