### ISSUE TITLE
Cookie Definitionen als YAML hinterlegen

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/iwcc#20]
Die Felder Name/Laufzeit/Beschreibung werden durch eine einzelne Textarea "Cookie Definitionen" ersetzt, die YAML erwartet:
```
-
  name: _ga
  time: 2 Jahre
  desc: Speichert für jeden Besucher der Website eine anonyme ID. Anhand der ID können Seitenaufrufe einem Besucher zugeordnet werden.
-
  name: _gat
  time: 1 Tag
  desc: Verhindert, dass in zu schneller Folge Daten an den Analytics Server übertragen werden.
-
  name: _gid
  time: 1 Tag
  desc: Speichert für jeden Besucher der Website eine anonyme ID. Anhand der ID können Seitenaufrufe einem Besucher zugeordnet werden.
```
Damit sind sämtliche Cookies für einen Dienst in einem Datensatz vorhanden, die Eingabe geht schneller und die Liste wird übersichtlicher.

**Comment by IngoWinter** [comment]
@skerbis gerne testen. du musst das addon neu installieren, weil sich die db geändert hat.

**Comment by skerbis** [comment]
thx
