### ISSUE TITLE
Deprecated: Non-static method iwcc_frontend::getFragment() should not be called statically in rex:///template/4 on line 56

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/iwcc#21]
Moin Ingo!
Eine Frage zu iwcc…
Ich habe da eine kleine Fehlermeldung:
Deprecated: Non-static method iwcc_frontend::getFragment() should not be called statically in rex:///template/4 on line 56
Da steht nur "REX_IWCC[]", sonst nix. Was mache ich falsch?
Danke :-)

**Comment by IngoWinter** [comment]
Du machst nix falsch. Die Warnmeldung taucht im neuesten Release nicht mehr auf :)
