### ISSUE TITLE
Probleme bei Mehrsprachigkeit

### ISSUE THREAD

**Issue by rolandsee** [FriendsOfREDAXO/iwcc#22]
Hi, ich entwickle zur Zeit eine Redaxo-Webseite, die DE/EN unterstützt.
Die Konfiguration/Einrichtung/Anzeige des AddOns für DE ist problemlos.

Für EN treten jedoch eine Ungereimheiten auf, die wohl so nicht gedacht waren. Gerne lasse ich mich aber auch eines besseren belehren.

1) Keine Möglichkeit, unter "Cookie Texte" die Einträge für die Sprache EN vornehmen zu können. Also zumindest das Übersetzen der schon vorhandenen DE Einträge:
![image](https://user-images.githubusercontent.com/4113894/69055226-99d5ce00-0a0d-11ea-8f5c-c194ca0a72bd.png)

versus

![image](https://user-images.githubusercontent.com/4113894/69054939-ef5dab00-0a0c-11ea-9d9d-2178b7632a04.png)

Damit kann dann auch für clang=2 nichts im Cookiebanner angezeigt werden.

2) "Cookie Gruppen" und "Cookies" werden für DE alle angezeigt, also DE und EN,
![image](https://user-images.githubusercontent.com/4113894/69055047-2f249280-0a0d-11ea-8191-c30cb660fd4b.png)

und

![image](https://user-images.githubusercontent.com/4113894/69055077-42376280-0a0d-11ea-97cf-47a881dd61d1.png)

während in EN  tatsächlich nur die für die Sprache relevanten Einträge gezeigt werden:
![image](https://user-images.githubusercontent.com/4113894/69055547-4f088600-0a0e-11ea-8deb-c02bbffb3c95.png)

und

![image](https://user-images.githubusercontent.com/4113894/69055197-8460a400-0a0d-11ea-80e5-757167dc093f.png)

Viele Grüße, Roland

**Comment by IngoWinter** [comment]
ist die neueste addon version im einsatz (1.0.3)?

**Comment by IngoWinter** [comment]
und wie ist das mit der zweiten sprache gelaufen - war die schon aktiv, als du das addon installiert hast?

**Comment by rolandsee** [comment]
yep, also die 1.0.3er aus dem Installer

in rex_iwcc_cookiegroup sind 6 Einträge vorhanden. Erwartet hätte ich vier
![image](https://user-images.githubusercontent.com/4113894/69056206-be32aa00-0a0f-11ea-9b67-4d8c61de9cfb.png)
Hab es vielleicht tatsächlich nicht ganz verstanden, was bei der Erstinstallation passiert.

**Comment by rolandsee** [comment]
Hi Ingo, ich habe mal testweise direkt in der DB die Tabellen für die Clang=2 gefüllt (rex_iwcc_text, rex_iwcc_cookiegroup, rex_iwcc_cookie). Nun sind die Daten in beiden Sprachen vollständig vorhanden.
Trotzdem werden die cookie_groups für die Sprache EN nicht geladen.
Hier das DE cookiegroup array (per dump in iwcc_box.php zeile 7):
![image](https://user-images.githubusercontent.com/4113894/69065126-84699f80-0a1f-11ea-8b3a-68b544f38979.png)
)
Hier in der EN Version:
![image](https://user-images.githubusercontent.com/4113894/69065190-a4995e80-0a1f-11ea-997c-8a3c2155091b.png)

**Comment by IngoWinter** [comment]
Am besten du installierst dir die 1.0.4, deinstallierst und installierst nochmal.

**Comment by rolandsee** [comment]
Hi Ingo, ich habe die neue 1.0.4 installiert (vorher alles sauber deinstalliert). Funzt nun wie erwartet. Ich werde das AddOn nun in zwei in der Entwicklung befindliche Webprojekte integrieren und verfolgen, ob mir sonst noch etwas auffällt.
Dann wird es wohl auch eine Donation geben, den dieses AddOn ist wirklich cool geworden.

**Comment by IngoWinter** [comment]
Astrein :)
