### ISSUE TITLE
Checkboxen und jew. Titel ein bisschen verrutscht

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/iwcc#23]
![Bildschirmfoto 2019-11-20 um 21 38 02](https://user-images.githubusercontent.com/45007596/69277049-d9541400-0bdf-11ea-9872-2a33511d8e7c.png)

**Comment by IngoWinter** [comment]
hallo @Geri2017 
da das ein css problem zu sein schein brauche ich browser und betriebssystem, bei dem das auftritt. ein link zur seite würde auch helfen.

**Comment by Geri2017** [comment]
Seite ist noch in Entwicklung.
Ansonsten MacOS 10.14.6 / Firefox Developer Edition 71.0b11 (64-Bit)

**Comment by IngoWinter** [comment]
Du bist sicher, dass da nicht dein eigenes CSS reingrätscht? Kann mir eigentlich nicht vorstellen, dass das auf einem aktuellen FF so aussieht - Mac hin oder her :)

**Comment by Geri2017** [comment]
Tritt nur auf, wenn:
statistics cookie ohne checkbox "diese Cookie Gruppe enthält die technisch notwendigen Cookies"
und checkboxen matomo oder google.
Wenn "technisch notwendigen Cookies" nicht angehakt, aber matomo oder google ausgewählt, dann kein Problem

**Comment by Geri2017** [comment]
Na so mies ist der Mac auch nicht :-)

**Comment by Geri2017** [comment]
Wie könnte ich denn checken, was da reingrätscht?

**Comment by IngoWinter** [comment]
Guck mit den Entwicklerwerkzeugen (F12) ob da irgendwelche von deinen Anweisungen greifen.

**Comment by skerbis** [comment]
<img width="1436" alt="Bildschirmfoto 2019-11-20 um 22 43 12" src="https://user-images.githubusercontent.com/791247/69280788-62bb1480-0be7-11ea-8e3e-ecda726086f9.png">
FF: 68.0b14 
macOS: 10.15
