### ISSUE TITLE
Scripte

### ISSUE THREAD

**Issue by Goldfischpeter** [FriendsOfREDAXO/iwcc#24]
Wie kann man abfragen
- ob der Schliessen-Button
- ob einer der beiden Buttons
geklickt wurde?

**Comment by IngoWinter** [comment]
Hier wird der Klick verarbeitet: https://github.com/FriendsOfREDAXO/iwcc/blob/master/assets/iwcc_frontend.js#L71-L87

**Comment by IngoWinter** [comment]
Was möchtest du denn machen?

**Comment by Goldfischpeter** [comment]
Nach einem Klick auf die Buttons soll der Hinweis nicht mehr erscheinen.
Oder das Tracking eingebunden werden.

**Comment by IngoWinter** [comment]
Cookie-Gedöhns ist eine OPT-IN Lösung - sprich nur wenn der Nutzer explizit sein Einverständnis zum Tracking gibt, darfst du im Anschluss ein Tracking Skript laden.
Wenn jemand die Box über das "x" wegklickt, hat er kein Einverständnis gegeben. Wenn jemand die Box über "Auswahl bestätigen" wegklickt und keinen Haken bei "Statistik" gesetzt hat, hat er kein Einverständnis gegeben.

**Comment by Goldfischpeter** [comment]
Ja, ich will  bei Klick auf das X, dass das Gedöns nicht mehr erscheint.
Und wenn er sein Einverständnis gegeben hat und auf "Auswahl bestätigen" klickt, soll das Gedöns auch nicht mehr erscheinen und das Tracking eingebunden werden.

**Comment by skerbis** [comment]
Der Klick auf das X sollte es nur abbrechen. Es sollte keine Zustimmung oder Ablehnung erfolgen. Es steht dir frei das Fragment zu ändern und es anders zu bauen

**Comment by IngoWinter** [comment]
Bei Klick auf X erscheint das Gedöns weiterhin, weil der Nutzer mit Klick auf X keine Cookie Auswahl speichert - er klickt halt nur die Box weg. Dieses Verhalten ist mit Leuten die sich auskennen abgesprochen :)

Wenn er sein Einverständnis gegeben hat und auf "Auswahl bestätigen" klickt passiert was du dir wünscht. Wenn du einen Anwenderfehler ausschliessen kannst und das Banner trotzdem immer wieder aufpoppt, mach bitte ein Issue dazu auf (zb "Auswahl wird nicht gespeichert").
