### ISSUE TITLE
Mehrsprachigkeit und die 2 Buttons “Auswahl bestätigen” und “Alle auswählen”

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/iwcc#28]
Ideal wäre es wenn man unter "Cookie Texte" auch den Text dieser 2 Buttons eingegeben könnte ...

**Comment by steri-rex** [comment]
das wäre super - wie kann man derzeit die 2 Buttons in eine andere Sprache übersetzen?

**Comment by steri-rex** [comment]
habs gefunden in: fragments/iwcc_box.php

**Comment by mbodon** [comment]
/redaxo/src/addons/iwcc/fragments/iwcc_box.php

**Comment by IngoWinter** [comment]
Die iwcc_box.php ist zwar prinzipiell richtig, wird aber beim nächsten Update überschrieben. @bitshiftersgmbh möchte da noch immer nen pr machen. Einfach mal im Slack anfragen: @el_pschulzo

**Comment by TobiasKrais** [comment]
Lösung wurde gerade gemerged.
