### ISSUE TITLE
Code pro Dienst festlegen, nicht pro Gruppe

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/iwcc#29]
Es wäre glaube ich besser, wenn der Code am Dienst hinterlegt wird (z.B. google-analytics), statt an der Cookie-Gruppe - denn am Dienst ist ja auch die logische Zugehörigkeit.

**Comment by IngoWinter** [comment]
Der Code wird am Dienst festgelegt und dann per Checkbox einer Gruppe zugeordnet. Oder verstehe ich dich falsch?

**Comment by alexplusde** [comment]
Der Code wird am Dienst festgelegt.

Die Zuordnung zur Gruppe wäre aber auch sinnvoll, direkt dort vornehmen zu können. Oder an beiden Stellen. Ist ja ne Relation, schätze ich.

**Comment by IngoWinter** [comment]
ich mach mal mangels Aktivität zu
