### ISSUE TITLE
Zweiklick-Lösung anbieten / nachträgliche Einwilligung

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/iwcc#30]
Nicht eingewilligten Cookies sollte man im Nachhinein noch zustimmen können, bspw. über eine 2-Klick-Lösung. Zufällig hatte ich da ja was angefangen...

https://github.com/alexplusde/2Click-Privacy

**Comment by IngoWinter** [comment]
Die Frage ist, wie man es umsetzen möchte. Ob zentral im Addon oder lieber doch in den einzelnen Modulen. Ich tendiere eher zu einer Lösung über die Module. Siehe auch https://github.com/FriendsOfREDAXO/iwcc/issues/26

**Comment by alexplusde** [comment]
Oder beides. Widerspricht sich ja nicht.

**Comment by IngoWinter** [comment]
Die billigste Variante wäre, deinem 2Click-Privacy Overlay noch die Klasse "iwcc-show-box" mitzugeben. Das würde automatisch die Box triggern. Aus den Funktionen wie "init_twitter" machst du was selbststartendes und das wars dann schon.

**Comment by alexplusde** [comment]
Eben

**Comment by IngoWinter** [comment]
Den Hinweistext für die verschiedenen Inhaltstypen könnte man bei den Diensten unterbringen, um speziell was zu Twitter, Maps etc. zu schreiben. Der Dienstschlüssel wäre dann das Äquivalent zum jetzigen "data-2click-type". Mach ma :)
