### ISSUE TITLE
Cookie: Datenschutzerklärung ist Text statt textarea

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/iwcc#31]
![image](https://user-images.githubusercontent.com/3855487/73664669-150b5f80-46a0-11ea-92f7-e31d91ec6274.png)

Ist das beabsichtigt / gewollt? Wie wird dieses Feld ausgelesen? Sollte es da sogar die Möglichkeit geben, HTML ein/auszugeben? (weiterführende Links, Listen, ...)

**Comment by IngoWinter** [comment]
Ich darf auf den entsprechenden Abschnitt in der readme verweisen - aus dem Screenshot wirds eigentlich recht klar. Hier kann ein Link eingesetzt werden.

**Comment by alexplusde** [comment]
Ah, so ist das gedacht. Für weitergehende Infos. Finde ich dennoch ungünstig. Ein Text kann mehr als einen Link beinhalten hierzu.

**Comment by IngoWinter** [comment]
Nicht für weiterführende Informationen, sondern für die Datenschutzerklärung. Mir ist bisher noch kein Dienst untergekommen, der seine Datenschutzerklärung auf mehrere Websites verteilt hat.

**Comment by alexplusde** [comment]
Ich euch dir Mal ein Beispiel raus ;D

**Comment by TobiasKrais** [comment]
Was wäre, wenn wir das Feld in "Link zur Datenschutzerklärung" umbenennen?

**Comment by IngoWinter** [comment]
@TobiasKrais machst du dazu einen PR fertig? Dann kann das Issue hier auch zu...

**Comment by TobiasKrais** [comment]
Ist erledigt. Das Feld ist umbenannt und damit selbsterklärend.

**Comment by IngoWinter** [comment]
Astrein, vielen Dank :)
