### ISSUE TITLE
Button "Auswahl bestätigen" "Alle auswählen" 

### ISSUE THREAD

**Issue by jeje-993** [FriendsOfREDAXO/iwcc#35]
Hallo,
ich nutze das "Cookie-Gedöns" für eine Webseite mit drei Sprachen, 98% der Texte lassen sich im AddOn übersetzen nur die zwei Button "Auswahl bestätigen" "Alle auswählen" lassen sich nicht übersetzen, ich hab es mit Platzhalter (Sprog) im der iwcc_box.php hat aber leider auch nicht geklappt.
Gruß
Jochen

**Comment by IngoWinter** [comment]
ist bekannt und @bitshiftersgmbh möchte da eine pr zu machen, siehe https://github.com/FriendsOfREDAXO/iwcc/issues/28
