### ISSUE TITLE
Platzhalter REX_IWCC[] abfangen

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/iwcc#39]
Moin,

vielleicht eher eine kleine kosmetische Sache, vermutlich läuft auch kaum jemand rein, aber spricht etwas dagegen das Ersetzen des Platzhalters `REX_IWCC[]` nochmal auf aktiviertes Addon zu validieren?

Habe den Cookie Hinweis gerade bei einem Kunden vorbereitet und anschließend das Addon deaktiviert und es hat etwas geknallt. Hab es jetzt im Template abgefangen, aber dann geht es weiter und `iwcc_frontend.js` schmeißt den nächsten Fehler, weil das Template Script nicht gefunden werden kann.

**Comment by IngoWinter** [comment]
Statt den Platzhalter zu nutzen kannst du das Gedöns HTML auch innerhalb einer Abfrage istAddonInstalliertundAktiviert per PHP einbinden https://github.com/FriendsOfREDAXO/iwcc/blob/master/lib/iwcc_frontend.php#L58. Kannst gerne die readme dementsprechend erweitern 👍

**Comment by pschuchmann** [comment]
Ok, aber das Problem mit dem JS besteht auch in dem Fall weiter, da es auf jeden Fall feuert. Wenn das Script nicht geladen wird, raucht das komplette JS ab. Ich schau mal, ob ich dir da was beisteuern kann in den nächsten Tagen.

**Comment by IngoWinter** [comment]
Das JS wird ebenfalls über den Platzhalter eingebunden https://github.com/FriendsOfREDAXO/iwcc/blob/master/fragments/iwcc_box.php - sollte eigentlich kein Problem geben. Vielleicht könnt man die Abfrage auch direkt ins Fragment einbauen.

**Comment by pschuchmann** [comment]
Hmm, da hast du wohl Recht. Rein von der Addon Logik läuft alles so wie es soll ;)

Bei dem Projekt hatte ich ein angepasstes Fragment und hab die Assets selbst geladen und das hat dann letztlich zum Fehler geführt.
