### ISSUE TITLE
box bei datenschutzerklärung/impressum nicht anzeigen

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/iwcc#4]

**Comment by skerbis** [comment]
Schien zwischendurch zu funktionieren. Im aktuellen Stand scheint es nicht mehr zu gehen. Der Hinweis bleibt geöffnet.

**Comment by IngoWinter** [comment]
Die Abfrage findet nach wie vor hier statt: https://github.com/FriendsOfREDAXO/iwcc/blob/master/lib/iwcc_frontend.php#L36
Was sich geändert hat, ist der Umbau auf REX_VAR. Die Ausgabe von `REX_IWCC[]` landet im Cache. Sprich wenn du als erstes eine Seite mit Box aufrufst, wird die Box immer gezeigt. Wenn du als erstes eine Seite ohne Box aufrufst, wird die Box auch auf anderen Seite nicht mehr gezeigt. 
@skerbis  weisst du aus dem Stegreif wie/ob man das Cachen verhindern kann?

**Comment by skerbis** [comment]
@IngoWinter schau mal wie ich's beim Global Settings AddOn gemacht habe. Da wird der Methodenaufruf zurückgegeben nicht die Ausgabe.

**Comment by IngoWinter** [comment]
@skerbis magst du nochmal reinstallieren und checken? vielleicht haben sich damit ja auch https://github.com/FriendsOfREDAXO/iwcc/issues/16 und https://github.com/FriendsOfREDAXO/iwcc/issues/17 erledigt

**Comment by skerbis** [comment]
sehe keine Besserung

**Comment by skerbis** [comment]
#17 ist gelöst.  Dieses hier nicht

**Comment by IngoWinter** [comment]
Hm. Ich habe mir extra gerade das GH zip gezogen und reinstalliert - bei mir funktionierts. Auf Impressum/Datenschutz bekommt die Box die Klasse "iwcc-initially-hidden" https://github.com/FriendsOfREDAXO/iwcc/blob/master/fragments/iwcc_box.php#L16
In der frontend.js checke ich das und zeige die Box dann nicht an https://github.com/FriendsOfREDAXO/iwcc/blob/master/assets/iwcc_frontend.js#L38-L40

Was steht denn in der Debug Ausgabe drin, wenn du `REX_IWCC[debug=1 forceCache=1]` setzt?
![Firefox_Screenshot_2019-11-12T13-46-51 491Z](https://user-images.githubusercontent.com/7223820/68676897-4968f700-055b-11ea-9a2e-f895cc17388c.png)

**Comment by skerbis** [comment]
Funktioniert ... vielleicht doch ein Cache-Problem gewesen
