### ISSUE TITLE
Fehlerseite 403 bei Domainweiterleitung nach dem Cookies akzeptiert wurden

### ISSUE THREAD

**Issue by jeje-993** [FriendsOfREDAXO/iwcc#40]
Es gibt eine Hauptdomains und eine Domain die auf die Hauptdomain weiterleitet, wenn ich jetzt von der Domain komme, die auf die Hauptdomain verweist, **und den Cookiebanner akzeptiere** wird die Seite nicht mehr angezeigt und Fehlerseite 403 angezeigt.

**Comment by IngoWinter** [comment]
hat sich wohl erledigt...
