### ISSUE TITLE
AddOnnamen und Präfix überdenken?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/iwcc#42]
Da jetzt Cookie consent archiviert wurde (gab es dazu eine Abstimmung?), könnte man dann hier den Namen Gedöns loswerden und eventuell auch das Präfix iw für Ingo Winter?

**Comment by IngoWinter** [comment]
Mir das vollkommen egal. Tob dich aus.

**Comment by tbaddade** [comment]
Ich würde es gern von FOR diskutieren lassen, sodass wir gemeinsam hier etwas finden.
Falls die Mehrheit bei dem bisherigen bleiben mag, auch ok.

**Comment by schuer** [comment]
»Cookies«

**Comment by tbaddade** [comment]
Ich

>> ich habe jetzt das Cookieteil umgesetzt und auf der Arbeitsdomain veröffentlicht.

Kunde
> Ich hab im ersten Moment Cocktail gelesen! :')

**Comment by IngoWinter** [comment]
ich mach mal mangels aktivität zu
