### ISSUE TITLE
2 Buttons + Link: Impressum können nicht übersetzt werden

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/iwcc#47]
Vorweg erst einmal vielen DANK für das tolle Addon !!!

Ich hab es nun erstmalig auf einer Webseite mit 3 Sprachen eingesetzt.
Es läßt sich ja alles super ersetzen, aber ich habe für nachfolgende 2 Buttons und das Wort Impressum bisher keine Möglichkeit gefunden.

`< a class="iwcc-save-selection iwcc-close" >Auswahl bestätigen< /a >`
`< a class="iwcc-accept-all iwcc-close" >Alle auswählen< /a >`

Und der Link-Text: Impressum

Habe ich da was übersehen oder kann man das ggf. noch editierbar machen ?

Ich hoffe ich kann mit solchen Hinweisen die Entwicklung zumindest etwas unterstützen.

Liebe Grüße und bleibt gesund
Mirco

**Comment by IngoWinter** [comment]
Ist bereits gefixt, siehe https://github.com/FriendsOfREDAXO/iwcc/pull/36
