### ISSUE TITLE
Schriftkonflikt

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/iwcc#48]
Hallo, iwcc führt zu einem Schriftkonflikt mit Fonts wie Font-Awesome oder Line-Icons.
In der fontello.css wird die Klasse "icon-" behandelt. Dieser Klassenname wird häufiger benutzt. Es wäre also gut die Iconklasse bei iwcc spezifischer zu machen, z.B. "iwccicon-"

fontello.css, Zeile 25
`[class^="icon-"]::before, [class*=" icon-"]::before {`

Gruß Heinz

**Comment by IngoWinter** [comment]
@erraiva @shauste macht einer von euch noch einen PR hierzu?

**Comment by NGWNGW** [comment]
#74 vielleicht?
