### ISSUE TITLE
"Indentation problem" beim speichern eines Cookies

### ISSUE THREAD

**Issue by simonsinus** [FriendsOfREDAXO/iwcc#50]
"Indentation problem" beim speichern eines Cookies
Generell jetzt überall, wo man "Speichern" kann.

**Comment by simonsinus** [comment]
Es lag an einer falschen YAML Syntax. Vielleicht sollte man einen YAML Syntax Checker vorschalten.

**Comment by IngoWinter** [comment]
Der könnte dann ne Warnung wie "Indentation problem" ausgeben :)
