### ISSUE TITLE
Unter Redaxo 5.9.0 probleme beim Installieren / Reinstallieren

### ISSUE THREAD

**Issue by simonsinus** [FriendsOfREDAXO/iwcc#51]
Datenbankfehler beim Installieren / Deinstalieren / Reinstallieren

**Comment by IngoWinter** [comment]
Zieh dir das Addon am besten direkt von hier, ist bereits gefixt https://github.com/FriendsOfREDAXO/iwcc/issues/37 aber noch nicht im Installer.
