### ISSUE TITLE
Detailanzeige - iwcc wie anpassen?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/iwcc#52]
<img width="866" alt="Bildschirmfoto 2020-05-15 um 10 35 04" src="https://user-images.githubusercontent.com/338267/82029864-e1c16f00-9697-11ea-80ad-d94fb6ea24b6.png">

Wie kann man das `iwcc` im Frontend anpassen?

**Comment by IngoWinter** [comment]
Im Backend bei der Cookie Definition. Oder ich verstehe die Frage nicht :)

**Comment by tbaddade** [comment]
> Im Backend bei der Cookie Definition. Oder ich verstehe die Frage nicht :)

Der Screen zeigt das Frontend, wenn man die Details sich zeigen lässt. Ich vermute jetzt, dass es der Key ist den man im Backend nicht ändern darf.

**Comment by IngoWinter** [comment]
Achso ja. Der Cookie, den das Addon zur Speicherung des Consents setzt, heisst nicht änderbar "iwcc".
