### ISSUE TITLE
Domains - aus System oder yrewrite verwenden?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/iwcc#53]
Jetzt müsste man an noch einer weiteren Stelle die Domains pflegen, was bei einer Multidomainseite recht aufwendig werden kann. Sobald yrewrite dabei ist, könnte man von dort die Domains verwenden und als Fallback die unter System hinterlegte.

**Comment by IngoWinter** [comment]
Wenn du so einen Fall hast (zig Domains auf einer Seite) und sich die Erweiterung für dich als wirtschaftlich darstellt, bau das gerne ein. Ich glaube @alexplusde hatte das auch schon mal angeregt.

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/iwcc/issues/44

**Comment by IngoWinter** [comment]
mangels interesse mach ich mal hier zu.
