### ISSUE TITLE
Verständnisfrage - Skripte, die nach Einverständnis geladen werden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/iwcc#54]
Aus der Readme

> Pro Gruppe können Skripte hinterlegt werden, die nach Akzeptieren der Gruppe ausgeführt werden.

Sind das Skripte die 
1. nur einmal nach akzeptieren der Gruppe ausgelöst werden oder 
2. sind das Skripte die ständig geladen werden, sofern das Einverständnis vorhanden ist

Wenn 2. zutrifft, wo erscheinen die Skripte im Quelltext?

**Comment by IngoWinter** [comment]
2. trifft zu, die Skripte werden in einem data Attribut im Fragment ausgegeben https://github.com/FriendsOfREDAXO/iwcc/blob/master/fragments/iwcc_box.php#L36 und bei Einverständnis durch den Nutzer aktiviert https://github.com/FriendsOfREDAXO/iwcc/blob/master/assets/iwcc_frontend.js#L134-L164

**Comment by tbaddade** [comment]
Danke … Wäre es sinnvoll, die Skripte vor dem `</body>` schreiben zu lassen?

**Comment by IngoWinter** [comment]
Keine Ahnung ob das sinnvoll wäre. Welches Problem würde das lösen?

**Comment by tbaddade** [comment]
> Welches Problem würde das lösen?

Dass das JS erst am Ende geladen wird.

**Comment by IngoWinter** [comment]
Die Scripte werden erst auf DomContentLoaded ins html eingehängt: https://github.com/FriendsOfREDAXO/iwcc/blob/master/assets/iwcc_frontend.js#L12
Ich schätze zu dem Zeitpunkt ist es uninteressant, an welcher Stelle im HTML der Skriptaufruf steht oder?

**Comment by tbaddade** [comment]
Stimmt auch wieder
