### ISSUE TITLE
Verständnisfrage : Cookie Gruppe bearbeiten

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/iwcc#56]
**Skripte, die nach Einverständnis geladen werden**

Wird das Skript nur einmalig nach dem Einverständnis geladen oder immer sofern das Cookie noch gesetzt ist?

Hintergrund ist, dass das Javascript nicht erscheint. Sollte man daher das Matomo Skript selbst in das Template notieren? Wie ist eure Erfahrung?

**Comment by IngoWinter** [comment]
solange im iwcc cookie das einverständnis für eine cookiegruppe gespeichert ist, werden die skripte dieser gruppe geladen. wenn irgendein skript trotz einverständnis für seine gruppe nicht geladen wird, müsste man mal gucken warum das so ist.

**Comment by tbaddade** [comment]
Ich hatte es dann direkt im Template untergebracht.

Ich schließe mal, da die eigentliche Frage ja beantwortet wurde.
