### ISSUE TITLE
Neue Textfelder für Buttons werden nicht angelegt

### ISSUE THREAD

**Issue by rolandsee** [FriendsOfREDAXO/iwcc#57]
Ich hatte eben den Fall, dass mit dem Upgrade von 1.0.8 auf 1.0.9 die neuen Textfelder für die beiden Buttons "button_select_all" und "button_accept" nicht in der DB (Tabelle rex_iwcc_text) angelegt wurden. Grundlage war die 1.0.9 aus github. Ich habe mir beholfen, in dem ich die Felder händisch in der DB angelegt habe. Sollte jedoch bei ReInstall automatisch funktionieren.

**Comment by IngoWinter** [comment]
Ich schätze, dass die update.php das Problem ist: https://github.com/FriendsOfREDAXO/iwcc/blob/master/update.php
Hier steht die ID für die neuen Datensätze als fixer Wert drin. @TobiasKrais

**Comment by TobiasKrais** [comment]
Sollte mit diesem [Commit](https://github.com/FriendsOfREDAXO/iwcc/commit/9a5c34e8474c38a04204e16a71ec9640a32608e0) behoben sein. Danke Ingo für den Tipp. Bugfix Release ist im Installer
