### ISSUE TITLE
Codemirror bei der Codeeingabe aktivieren

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/iwcc#58]

**Comment by IngoWinter** [comment]
Wenn Codemirror über das customizer Plugin geladen ist, wird YAML gehübscht https://github.com/FriendsOfREDAXO/iwcc/commit/30121b3b880073bc7b48a9d22a28481bcd5d01ae

**Comment by IngoWinter** [comment]
Hat nicht funktioniert und ist deswegen in 1.1.1 wieder rausgeflogen. Anscheinend werden die Eingaben im Codemirrror Editor nicht in die originale textarea übertragen, zudem entfernt das Customizer Plugin das name Attribut der textarea, wodurch nix gespeichert wird.

**Comment by IngoWinter** [comment]
Funktioniert doch, wenn man mit rex_form umgehen kann: https://github.com/redaxo/redaxo/issues/3846
Eingebaut in https://github.com/FriendsOfREDAXO/iwcc/pull/81
