### ISSUE TITLE
Wunsch: Cookies importieren oder via yform bearbeiten?

### ISSUE THREAD

**Issue by anveno** [FriendsOfREDAXO/iwcc#63]
Aufgrund der pid als auto-increment-Wert und eines weiteren id-Feldes, lässt sich die Tabelle nicht mit yform bearbeiten um so z.B. schnell Cookies zu importieren. Gibt es eine andere Möglichkeit dazu, um nicht bei jeder neuen Installation die Cookies per Hand einzutragen?

**Comment by IngoWinter** [comment]
Von mir aus packs hierein: https://github.com/FriendsOfREDAXO/iwcc/blob/master/install.sql

**Comment by IngoWinter** [comment]
@skerbis was meinst du?
