### ISSUE TITLE
Breite Cookiemeldung Smartphone

### ISSUE THREAD

**Issue by jfax** [FriendsOfREDAXO/iwcc#67]
Hallo, in schmaler Responsiveansicht klebt der weiße Banner arg rechts am Rand. Falls nachvollziehbar: [Eine Veränderung](https://github.com/FriendsOfREDAXO/iwcc/blob/master/scss/iwcc_frontend.scss#L22) von 100 auf 80% bringt bei mir ein ordentliches Erlebnis. Danke für das guten Addon

**Comment by IngoWinter** [comment]
Danke für die Meldung, aber das "Kleben" dürfte von deinem eigenen CSS ausgelöst worden sein :)
