### ISSUE TITLE
Alternativer Datenimport nötig

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/iwcc#75]
Es gibt eine [install.sql](https://github.com/FriendsOfREDAXO/iwcc/blob/master/install.sql) über die Cookies und Cookie Gruppen in die Datenbank geschrieben werden, um den Einstieg zu erleichtern. Da steht auch die id der Datensätze drin. Die id ist wegen Mehrsprachigkeit nicht unique, die Cookie Gruppe "analytics" hat in jeder Sprache dieselbe id.

Wenn ich Cookies oder Cookie Gruppen lösche und dann einen Reinstall mache, schreibt mir die install.sql die gelöschten Datensätze erneut rein. Danach habe ich evt ids doppelt vergeben und die Fee ist am Arsch. Deswegen müssen Cookies und Cookie Gruppen aus der install.sql raus.

Ideen wie man den initialen Import anders lösen willkommen.

**Comment by marcohanke** [comment]
Wie ist denn der Plan? Ich teste gerade 2.0 und so ganz ohne Import ist wirklich doof.

**Comment by IngoWinter** [comment]
Aktuell gibt es noch keinen Plan. Bis v2 stable/bugfei ist, wollte ich es bei einem manuellen SQL Import wie in https://gist.github.com/IngoWinter/31df14685b45ad8980aadaec1e757363 belassen. Oder einen Dump zur Verfügung stellen, der über das Backup Addon geladen werden kann.

**Comment by IngoWinter** [comment]
Wie wäre es denn, wenn ich bei der Installation eine `iwcc_example_config.sql` ins data Verzeichnis des Backup Addons kopiere? Dann ist der Import auch noch derbst spannend, weil obendrüber was von Datenbank gelöscht steht :)

![Screenshot_2020-08-27 Vom Server laden · r5 loc · REDAXO CMS](https://user-images.githubusercontent.com/7223820/91444418-ff949780-e874-11ea-8072-1a3b1408c332.png)

**Comment by skerbis** [comment]
Biete doch einfach einen Import auf der AddOn-Seite an

**Comment by IngoWinter** [comment]
Mit 2.0.0-beta3 gibt es nun einen Reiter Setup. Dort kann der Nutzer manuell einen Dump einspielen, vorher werden alle betroffenen Tabellen geleert
