### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/iwcc#8]
![image](https://user-images.githubusercontent.com/330516/68568215-4dadeb00-045b-11ea-9fb9-ed4369e5ba93.png)

**Comment by IngoWinter** [comment]
sieht aus als käme das vom cookie consent addon

**Comment by olien** [comment]
up. ok. sorry

**Comment by IngoWinter** [comment]
ich bin froh, wenn sich alle issues so schnell erledigen :+1:
