### ISSUE TITLE
Cookie-Gruppen deaktivierbar machen

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/iwcc#87]
Es wäre toll, wenn man die Cookie-Gruppen neben "löschen" einfach nur "on/offline" schalten könnte.
Dann kann man z.B. bereits angelegte Vorgaben bei Bedarf später zuschalten.

**Comment by IngoWinter** [comment]
Wenn eine Gruppe keiner Domain zugeordnet ist, ist sie "offline".
