### ISSUE TITLE
Keine Ausgabe IWCC-CSS+Scripte wenn zugestimmt wurde

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/iwcc#98]
Wenn zugestimmt wurde sollte kein Code vom IWCC mehr ausgegeben werden. 

Erst wieder Ausgabe wenn das Cookie abgelaufen ist und auch der Dialog ausgegeben werden muss.

**Comment by IngoWinter** [comment]
Da die Cookiebox jederzeit aufgerufen werden kann, ist das keine gute Idee :)

**Comment by aeberhard** [comment]
Ah ok, Dachte wenn man die akzeptiert hat dann gut :)
